apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amit-dev-main
  namespace: argocd
spec:
  destination:
    namespace: amit-dev-main
    server: https://kubernetes.default.svc
  project: argocd-amit
  source:
    path: amit-dev-main/
    repoURL: https://github.com/amitrei/argocd-tests.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
